// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEu7Dus8RJfJ7MNUoDf7Ckg3QIvYX_6Z4',
    appId: '1:608132833436:web:570964ce60bf7479980d59',
    messagingSenderId: '608132833436',
    projectId: 'bongkar-68f66',
    authDomain: 'bongkar-68f66.firebaseapp.com',
    databaseURL: 'https://bongkar-68f66-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bongkar-68f66.firebasestorage.app',
    measurementId: 'G-J0SPG1BFGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCqF4yGonQyKTO_NAvG2n7ev1rnd8R1mw',
    appId: '1:608132833436:android:bc86ccba63d8213c980d59',
    messagingSenderId: '608132833436',
    projectId: 'bongkar-68f66',
    databaseURL: 'https://bongkar-68f66-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bongkar-68f66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqzwgCX8k7-py49cW8aSJ9bVdukWTydyo',
    appId: '1:608132833436:ios:c1328c13aba8c03f980d59',
    messagingSenderId: '608132833436',
    projectId: 'bongkar-68f66',
    databaseURL: 'https://bongkar-68f66-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bongkar-68f66.firebasestorage.app',
    iosBundleId: 'com.example.practApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqzwgCX8k7-py49cW8aSJ9bVdukWTydyo',
    appId: '1:608132833436:ios:c1328c13aba8c03f980d59',
    messagingSenderId: '608132833436',
    projectId: 'bongkar-68f66',
    databaseURL: 'https://bongkar-68f66-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bongkar-68f66.firebasestorage.app',
    iosBundleId: 'com.example.practApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEu7Dus8RJfJ7MNUoDf7Ckg3QIvYX_6Z4',
    appId: '1:608132833436:web:5560eb8b0c010278980d59',
    messagingSenderId: '608132833436',
    projectId: 'bongkar-68f66',
    authDomain: 'bongkar-68f66.firebaseapp.com',
    databaseURL: 'https://bongkar-68f66-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bongkar-68f66.firebasestorage.app',
    measurementId: 'G-XDWEFGVGND',
  );
}
